### ISSUE TITLE
Comfy node

### ISSUE THREAD

**Issue by ghost** [pOpsPaper/pOps#1]
Hi,
This looks fantastic! Is there or will there be a ComfyUI node for this please? 

Thank you!

**Comment by pOpsPaper** [comment]
Thanks! We don't have the capacity to work on that at the moment, but that seems like a cool idea.
Hopefully someone might give it a try

**Comment by smthemex** [comment]
I have made a ComfyUI node,  https://github.com/smthemex/ComfyUI_Pops

**Comment by ghost** [comment]
The word hero is underused
