### ISSUE TITLE
NameError: name 'EXAMPLE_INTERPOLATE_DOC_STRING' is not defined

### ISSUE THREAD

**Issue by zmy-08** [pOpsPaper/pOps#3]
This is truly a job that one can enjoy, it's fantastic. I encountered a problem when running the code, how can I solve this issue?
![b](https://github.com/pOpsPaper/pOps/assets/97605205/c828b1bc-327e-423a-ae81-22eadf0324b6)

**Comment by eladrich** [comment]
Thanks! Fixed in latest commit
